"""Re-syncing database schema

Revision ID: 14e6ef9568a0
Revises: 3b2988303522
Create Date: 2025-02-01 04:56:59.936898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14e6ef9568a0'
down_revision = '3b2988303522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("restaurant", schema=None) as batch_op:
        batch_op.add_column(sa.Column("rating", sa.Integer(), nullable=False, server_default="5"))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
