"""Add items relationship to Restaurant

Revision ID: 56348029bdcf
Revises: ecc054b5118d
Create Date: 2025-02-05 08:39:23.040696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56348029bdcf'
down_revision = 'ecc054b5118d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
