"""Add user_id to Order

Revision ID: 7bcd449c7c6b
Revises: ee8b95248dfe
Create Date: 2025-02-05 06:39:28.027723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bcd449c7c6b'
down_revision = 'ee8b95248dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
       batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
       batch_op.create_foreign_key('fk_order_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
