"""Added MenuItem model

Revision ID: a53bb42b10b9
Revises: 72c3d83029c0
Create Date: 2025-02-01 04:32:55.179613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a53bb42b10b9'
down_revision = '72c3d83029c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_item_restaurant', type_='foreignkey')
        batch_op.create_foreign_key('fk_item_restaurant', 'restaurant', ['restaurant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_item_restaurant', type_='foreignkey')
        batch_op.create_foreign_key('fk_item_restaurant', 'restaurant', ['restaurant_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
