"""Add balance to Restaurant

Revision ID: ecc054b5118d
Revises: 7bcd449c7c6b
Create Date: 2025-02-05 08:35:00.442162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecc054b5118d'
down_revision = '7bcd449c7c6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text("'100.0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'100.0'"))

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_column('balance')

    # ### end Alembic commands ###
