"""empty message

Revision ID: ee8b95248dfe
Revises: 79e9019973ab
Create Date: 2025-02-05 06:22:48.157983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee8b95248dfe'
down_revision = '79e9019973ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_order_user', 'user', ['user_id'], ['id'])
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key('fk_order_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
